In [2]:
from sklearn.metrics import mean_absolute_error
import numpy as np

In [3]:
a = np.array([0, 1, 2, 3])

b = np.array([5, 4, 3, 2])

In [1]:
import argparse
import os
import torch
import yaml
import pickle as pkl

from model.embed import DataEmbedding

import xgboost as xgb

from data.argparser import args_parsing

import numpy as np
from datetime import datetime

now = datetime.now().strftime("%d-%m-%Y_%H-%M-%S")
from data.data_loader import Dataset_XGB
from utils.postprocessing import ProcessedResult

from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_absolute_error

from model.embed import DataEmbedding

from torch.utils.data import DataLoader

c:\Users\cle\AppData\Local\miniforge3\envs\test\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
path = os.path.abspath('D:\srl_other_models\data\processed\SRL')

In [5]:
data = Dataset_XGB(
    root_path=os.path.abspath('D:\srl_other_models\data\dummy_dataset'),
    data_path='SRL_NEG_00_04_dummy.csv',
    flag='train',
    size=[5, 1],
    scale=None
)

In [18]:
np.array(data.seqs_x).reshape(-1, 5)
# np.array(data.seqs_x_mark).reshape(-1, 5)

array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11],
       [ 8,  9, 10, 11, 12],
       [ 9, 10, 11, 12, 13]], dtype=int64)

In [31]:
x_matrix = np.array(data.seqs_x).reshape(-1, 5)
mark_matrix = np.array(data.seqs_x_mark).reshape(9, 3)

ValueError: cannot reshape array of size 135 into shape (9,3)

In [33]:
np.array(data.seqs_x_mark).shape

(9, 5, 3)

In [30]:
np.concatenate((x_matrix, mark_matrix), 1).shape

(9, 20)

In [28]:
mark_matrix

array([[11,  2,  0, 11,  3,  1, 11,  4,  2, 11,  5,  3, 11,  6,  4],
       [11,  3,  1, 11,  4,  2, 11,  5,  3, 11,  6,  4, 11,  7,  5],
       [11,  4,  2, 11,  5,  3, 11,  6,  4, 11,  7,  5, 11,  8,  6],
       [11,  5,  3, 11,  6,  4, 11,  7,  5, 11,  8,  6, 11,  9,  0],
       [11,  6,  4, 11,  7,  5, 11,  8,  6, 11,  9,  0, 11, 10,  1],
       [11,  7,  5, 11,  8,  6, 11,  9,  0, 11, 10,  1, 11, 11,  2],
       [11,  8,  6, 11,  9,  0, 11, 10,  1, 11, 11,  2, 11, 12,  3],
       [11,  9,  0, 11, 10,  1, 11, 11,  2, 11, 12,  3, 11, 13,  4],
       [11, 10,  1, 11, 11,  2, 11, 12,  3, 11, 13,  4, 11, 14,  5]],
      dtype=int64)

In [16]:
np.array(data.seqs_x).shape

(9, 5, 1)

In [20]:
np.array(data.seqs_x_mark)

array([[[11,  2,  0],
        [11,  3,  1],
        [11,  4,  2],
        [11,  5,  3],
        [11,  6,  4]],

       [[11,  3,  1],
        [11,  4,  2],
        [11,  5,  3],
        [11,  6,  4],
        [11,  7,  5]],

       [[11,  4,  2],
        [11,  5,  3],
        [11,  6,  4],
        [11,  7,  5],
        [11,  8,  6]],

       [[11,  5,  3],
        [11,  6,  4],
        [11,  7,  5],
        [11,  8,  6],
        [11,  9,  0]],

       [[11,  6,  4],
        [11,  7,  5],
        [11,  8,  6],
        [11,  9,  0],
        [11, 10,  1]],

       [[11,  7,  5],
        [11,  8,  6],
        [11,  9,  0],
        [11, 10,  1],
        [11, 11,  2]],

       [[11,  8,  6],
        [11,  9,  0],
        [11, 10,  1],
        [11, 11,  2],
        [11, 12,  3]],

       [[11,  9,  0],
        [11, 10,  1],
        [11, 11,  2],
        [11, 12,  3],
        [11, 13,  4]],

       [[11, 10,  1],
        [11, 11,  2],
        [11, 12,  3],
        [11, 13,  4],
        [11, 14,

In [13]:
data_loader = DataLoader(
    data,
    batch_size=9,
    shuffle=False,
    num_workers=1,
    drop_last=False)

In [5]:
data_emb = DataEmbedding(1, 32, 'fixed', 'd', 0.05)

In [9]:
data_emb(data.seqs_x, data.seqs_x_date)

AttributeError: 'list' object has no attribute 'permute'

In [ ]:
[i* 5 for i in range(1:10)]